# Generated by Django 5.2.7 on 2025-10-28 21:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0004_agent_enabled_tools_agent_tools_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL to send webhook events to', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('event_types', models.JSONField(default=list, help_text='List of event types to subscribe to')),
                ('secret', models.CharField(help_text='Secret key for HMAC signature verification', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable webhook')),
                ('description', models.TextField(blank=True, help_text='Optional description of webhook purpose')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retry attempts')),
                ('retry_delay_seconds', models.IntegerField(default=60, help_text='Initial delay between retries (exponential backoff)')),
                ('timeout_seconds', models.IntegerField(default=30, help_text='HTTP request timeout in seconds')),
                ('total_deliveries', models.IntegerField(default=0, help_text='Total number of delivery attempts')),
                ('successful_deliveries', models.IntegerField(default=0, help_text='Number of successful deliveries')),
                ('failed_deliveries', models.IntegerField(default=0, help_text='Number of failed deliveries')),
                ('last_delivery_at', models.DateTimeField(blank=True, help_text='Timestamp of last delivery attempt', null=True)),
                ('last_success_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful delivery', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Specific agent to subscribe to (optional, leave blank for all)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='agents.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'webhook',
                'verbose_name_plural': 'webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Type of event that triggered webhook', max_length=50)),
                ('payload', models.JSONField(help_text='Event payload sent to webhook')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('attempt_count', models.IntegerField(default=0, help_text='Number of delivery attempts made')),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='Scheduled time for next retry', null=True)),
                ('response_status_code', models.IntegerField(blank=True, help_text='HTTP status code from webhook endpoint', null=True)),
                ('response_body', models.TextField(blank=True, help_text='Response body from webhook endpoint')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Timestamp when successfully delivered', null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhook')),
            ],
            options={
                'verbose_name': 'webhook delivery',
                'verbose_name_plural': 'webhook deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['user', 'is_active'], name='webhooks_we_user_id_51012d_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['agent', 'is_active'], name='webhooks_we_agent_i_013a32_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['event_types'], name='webhooks_we_event_t_dc7f83_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['webhook', 'status'], name='webhooks_we_webhook_322278_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status', 'next_retry_at'], name='webhooks_we_status_eb2625_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['created_at'], name='webhooks_we_created_d5a8af_idx'),
        ),
    ]
