# Generated by Django 5.2.7 on 2025-10-20 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the agent', max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Brief description of agent purpose', verbose_name='description')),
                ('use_case', models.CharField(choices=[('support', 'Customer Support'), ('research', 'Research & Analysis'), ('automation', 'Workflow Automation'), ('scheduling', 'Smart Scheduling'), ('knowledge', 'Knowledge Management'), ('sales', 'Sales & Lead Generation')], default='support', help_text='Primary use case for this agent', max_length=20, verbose_name='use case')),
                ('prompt_template', models.TextField(blank=True, default='', help_text='System prompt template for the agent', verbose_name='prompt template')),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='LLM and tool configuration (provider, model, temperature, etc.)', verbose_name='configuration')),
                ('integration_hooks', models.JSONField(blank=True, default=dict, help_text='Webhook URLs, API keys, channel configs for integrations', verbose_name='integration hooks')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this agent is active and available for use', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this agent', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'agent',
                'verbose_name_plural': 'agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='knowledge/')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='agents.agent')),
            ],
            options={
                'verbose_name': 'knowledge base',
                'verbose_name_plural': 'knowledge bases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['user', '-created_at'], name='agents_agen_user_id_c13f11_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['use_case'], name='agents_agen_use_cas_a09de5_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['is_active'], name='agents_agen_is_acti_e9c14d_idx'),
        ),
    ]
