# Generated by Django 5.2.7 on 2025-10-28 16:18

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_toolexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Text content of this chunk', verbose_name='content')),
                ('embedding', pgvector.django.VectorField(blank=True, dimensions=1536, null=True)),
                ('chunk_index', models.IntegerField(help_text='Position of this chunk in the document', verbose_name='chunk index')),
                ('token_count', models.IntegerField(default=0, help_text='Approximate token count', verbose_name='token count')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Chunk-specific metadata (page number, section, etc.)', verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'document chunk',
                'verbose_name_plural': 'document chunks',
                'ordering': ['knowledge_base', 'chunk_index'],
            },
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='chunk_overlap',
            field=models.IntegerField(default=200, help_text='Overlap between chunks', verbose_name='chunk overlap'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='chunk_size',
            field=models.IntegerField(default=1000, help_text='Size of text chunks for embedding', verbose_name='chunk size'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='document_type',
            field=models.CharField(choices=[('text', 'Plain Text'), ('pdf', 'PDF Document'), ('docx', 'Word Document'), ('csv', 'CSV File'), ('json', 'JSON Data'), ('html', 'HTML Content'), ('markdown', 'Markdown')], default='text', max_length=20, verbose_name='document type'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash for deduplication', max_length=64, verbose_name='file hash'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True, verbose_name='file size'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional document metadata (author, date, etc.)', verbose_name='metadata'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='processed at'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed', verbose_name='processing error'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='total_chunks',
            field=models.IntegerField(default=0, help_text='Number of chunks created', verbose_name='total chunks'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='content',
            field=models.TextField(blank=True, help_text='Extracted or raw text content', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='file_path',
            field=models.FileField(blank=True, help_text='Uploaded document file', null=True, upload_to='knowledge/%Y/%m/%d/', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='title',
            field=models.CharField(help_text='Document title or filename', max_length=255, verbose_name='title'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['agent', 'status'], name='agents_know_agent_i_74662d_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['file_hash'], name='agents_know_file_ha_6b5425_idx'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='agents.knowledgebase'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['knowledge_base', 'chunk_index'], name='agents_docu_knowled_6abedf_idx'),
        ),
    ]
