# Generated by Django 5.2.7 on 2025-10-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_documentchunk_knowledgebase_chunk_overlap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='enabled_tools',
            field=models.JSONField(blank=True, default=list, help_text='List of enabled tool names for this agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='tools_config',
            field=models.JSONField(blank=True, default=dict, help_text='Tool-specific configuration settings'),
        ),
    ]
