# Generated by Django 5.2.7 on 2025-11-01 04:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_enabled_tools_agent_tools_config'),
        ('chat', '0006_conversation_channel_identifier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('query', 'Query'), ('response', 'Response'), ('feedback', 'Feedback'), ('handoff', 'Handoff')], max_length=50)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('uninstalled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-installed_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentOrchestration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of orchestration workflow', max_length=255)),
                ('strategy', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel'), ('conditional', 'Conditional'), ('hierarchical', 'Hierarchical')], default='sequential', max_length=20)),
                ('workflow_config', models.JSONField(default=dict, help_text='\n        {\n            "steps": [\n                {\n                    "agent_id": 1,\n                    "condition": "always|if_needed",\n                    "inputs": ["query", "previous_output"],\n                    "timeout_seconds": 30\n                }\n            ],\n            "synthesis_strategy": "concatenate|summarize|vote",\n            "max_parallel_agents": 3\n        }\n        ')),
                ('is_active', models.BooleanField(default=True)),
                ('total_executions', models.IntegerField(default=0)),
                ('successful_executions', models.IntegerField(default=0)),
                ('average_execution_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Orchestration',
                'verbose_name_plural': 'Agent Orchestrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('review_text', models.TextField()),
                ('helpful_count', models.IntegerField(default=0)),
                ('not_helpful_count', models.IntegerField(default=0)),
                ('publisher_response', models.TextField(blank=True)),
                ('publisher_response_date', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='User has actually installed the agent')),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tool name (e.g., "Get Weather Data")', max_length=255)),
                ('slug', models.SlugField(help_text='Unique identifier (auto-generated)', max_length=255)),
                ('description', models.TextField(help_text='What this tool does')),
                ('tool_type', models.CharField(choices=[('api', 'API Call'), ('webhook', 'Webhook'), ('database', 'Database Query'), ('script', 'Python Script'), ('http', 'HTTP Request')], default='api', max_length=20)),
                ('icon', models.CharField(default='🔧', help_text='Emoji or icon identifier', max_length=50)),
                ('endpoint_url', models.URLField(help_text='API endpoint URL', max_length=500)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('auth_type', models.CharField(choices=[('none', 'No Authentication'), ('api_key', 'API Key'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('oauth2', 'OAuth 2.0'), ('custom', 'Custom Headers')], default='none', max_length=20)),
                ('auth_config', models.JSONField(blank=True, default=dict, help_text='Authentication configuration (encrypted)')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Custom headers as key-value pairs')),
                ('parameters', models.JSONField(default=list, help_text='List of input parameters with types and descriptions')),
                ('request_body_template', models.TextField(blank=True, help_text='JSON template for request body with {{parameter}} placeholders')),
                ('response_mapping', models.JSONField(blank=True, default=dict, help_text='Map response fields to output format')),
                ('success_response_path', models.CharField(blank=True, help_text='JSON path to success data (e.g., "data.results")', max_length=255)),
                ('error_response_path', models.CharField(blank=True, help_text='JSON path to error message', max_length=255)),
                ('test_parameters', models.JSONField(blank=True, default=dict, help_text='Sample parameters for testing')),
                ('last_test_result', models.JSONField(blank=True, default=dict, help_text='Result of last test execution')),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Allow other users to use this tool')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('category', models.CharField(blank=True, help_text='Tool category', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HybridSearchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_weight', models.FloatField(default=0.7, help_text='Weight for vector similarity (0-1)')),
                ('keyword_weight', models.FloatField(default=0.3, help_text='Weight for keyword matching (0-1)')),
                ('rerank_enabled', models.BooleanField(default=True, help_text='Enable reranking of search results')),
                ('rerank_model', models.CharField(default='cross-encoder/ms-marco-MiniLM-L-6-v2', help_text='Model for reranking', max_length=100)),
                ('rerank_top_k', models.IntegerField(default=20, help_text='Number of results to rerank')),
                ('es_index_name', models.CharField(blank=True, help_text='Elasticsearch index name', max_length=255)),
                ('es_enabled', models.BooleanField(default=False, help_text='Enable Elasticsearch for keyword search')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hybrid Search Configuration',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Public name for marketplace', max_length=255)),
                ('tagline', models.CharField(help_text='Short description (one-liner)', max_length=200)),
                ('description', models.TextField(help_text='Detailed description')),
                ('category', models.CharField(choices=[('support', 'Customer Support'), ('research', 'Research & Analysis'), ('sales', 'Sales & Marketing'), ('productivity', 'Productivity'), ('creative', 'Creative & Content'), ('finance', 'Finance & Accounting'), ('hr', 'HR & Recruitment'), ('education', 'Education & Training'), ('other', 'Other')], default='other', max_length=20)),
                ('tags', models.JSONField(default=list, help_text='List of tags for search')),
                ('logo_url', models.URLField(blank=True, help_text='Logo image URL')),
                ('screenshots', models.JSONField(blank=True, default=list, help_text='List of screenshot URLs')),
                ('demo_video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price in USD', max_digits=10)),
                ('install_count', models.IntegerField(default=0)),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('rating_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured on marketplace homepage')),
                ('documentation_url', models.URLField(blank=True)),
                ('support_url', models.URLField(blank=True)),
                ('changelog', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('required_integrations', models.JSONField(default=list, help_text='List of required integration types')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Marketplace Agent',
                'verbose_name_plural': 'Marketplace Agents',
                'ordering': ['-is_featured', '-install_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrchestrationExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('execution_graph', models.JSONField(default=dict, help_text='DAG of agent executions with inputs/outputs')),
                ('final_response', models.TextField(blank=True)),
                ('agent_outputs', models.JSONField(default=dict, help_text='Individual agent outputs keyed by agent_id')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('failed_agent_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrchestrationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Role of agent in orchestration (e.g., researcher, validator)', max_length=50)),
                ('execution_order', models.IntegerField(default=0, help_text='Order in sequential execution (0 for parallel)')),
                ('is_optional', models.BooleanField(default=False, help_text='Whether agent execution is optional')),
            ],
            options={
                'ordering': ['execution_order'],
            },
        ),
        migrations.CreateModel(
            name='QueryExpansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_query', models.TextField()),
                ('expanded_queries', models.JSONField(default=list, help_text='List of expanded/synonymous queries')),
                ('use_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewHelpfulness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Review Helpfulness Votes',
            },
        ),
        migrations.CreateModel(
            name='ToolParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parameter_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('array', 'Array'), ('object', 'Object'), ('date', 'Date'), ('datetime', 'DateTime'), ('file', 'File')], default='string', max_length=20)),
                ('description', models.TextField(help_text='What this parameter does')),
                ('is_required', models.BooleanField(default=True)),
                ('default_value', models.CharField(blank=True, help_text='Default value if not provided', max_length=255)),
                ('validation_regex', models.CharField(blank=True, help_text='Regex pattern for validation', max_length=255)),
                ('enum_values', models.JSONField(blank=True, default=list, help_text='List of allowed values')),
                ('min_value', models.FloatField(blank=True, help_text='Minimum value (for numbers)', null=True)),
                ('max_value', models.FloatField(blank=True, help_text='Maximum value (for numbers)', null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='toolexecution',
            options={'ordering': ['-executed_at']},
        ),
        migrations.RenameField(
            model_name='toolexecution',
            old_name='created_at',
            new_name='executed_at',
        ),
        migrations.RemoveField(
            model_name='toolexecution',
            name='input_data',
        ),
        migrations.RemoveField(
            model_name='toolexecution',
            name='tool_name',
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this knowledge base is active', verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='toolexecution',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_executions', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='toolexecution',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='toolexecution',
            name='execution_time_ms',
            field=models.IntegerField(blank=True, help_text='Execution time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='toolexecution',
            name='input_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolexecution',
            name='status_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='toolexecution',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='toolexecution',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_executions', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='toolexecution',
            name='output_data',
            field=models.JSONField(),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['agent', 'is_active'], name='agents_know_agent_i_b6ee46_idx'),
        ),
        migrations.AddField(
            model_name='agentcommunication',
            name='from_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_communications', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='agentcommunication',
            name='to_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_communications', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='agentinstallation',
            name='installed_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_source', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='agentinstallation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentorchestration',
            name='orchestrator_agent',
            field=models.ForeignKey(help_text='Main agent that coordinates workflow', on_delete=django.db.models.deletion.CASCADE, related_name='orchestrations_as_orchestrator', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='agentorchestration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orchestrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentreview',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='agents.agentinstallation'),
        ),
        migrations.AddField(
            model_name='agentreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customtool',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toolexecution',
            name='custom_tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='agents.customtool'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['custom_tool', '-executed_at'], name='agents_tool_custom__ae3106_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['agent', '-executed_at'], name='agents_tool_agent_i_ef345f_idx'),
        ),
        migrations.AddField(
            model_name='hybridsearchconfig',
            name='knowledge_base',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hybrid_search_config', to='agents.knowledgebase'),
        ),
        migrations.AddField(
            model_name='marketplaceagent',
            name='agent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listing', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='marketplaceagent',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_agents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentreview',
            name='marketplace_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='agents.marketplaceagent'),
        ),
        migrations.AddField(
            model_name='agentinstallation',
            name='marketplace_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='agents.marketplaceagent'),
        ),
        migrations.AddField(
            model_name='orchestrationexecution',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orchestration_executions', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='orchestrationexecution',
            name='orchestration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='agents.agentorchestration'),
        ),
        migrations.AddField(
            model_name='agentcommunication',
            name='execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='agents.orchestrationexecution'),
        ),
        migrations.AddField(
            model_name='orchestrationparticipant',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent'),
        ),
        migrations.AddField(
            model_name='orchestrationparticipant',
            name='orchestration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agentorchestration'),
        ),
        migrations.AddField(
            model_name='agentorchestration',
            name='participant_agents',
            field=models.ManyToManyField(related_name='orchestrations_as_participant', through='agents.OrchestrationParticipant', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='queryexpansion',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_expansions', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='reviewhelpfulness',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpfulness_votes', to='agents.agentreview'),
        ),
        migrations.AddField(
            model_name='reviewhelpfulness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toolparameter',
            name='custom_tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_definitions', to='agents.customtool'),
        ),
        migrations.AddIndex(
            model_name='customtool',
            index=models.Index(fields=['user', 'is_active'], name='agents_cust_user_id_282bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='customtool',
            index=models.Index(fields=['tool_type', 'is_public'], name='agents_cust_tool_ty_5e8581_idx'),
        ),
        migrations.AddIndex(
            model_name='customtool',
            index=models.Index(fields=['slug'], name='agents_cust_slug_32702d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customtool',
            unique_together={('user', 'slug')},
        ),
        migrations.AddIndex(
            model_name='marketplaceagent',
            index=models.Index(fields=['status', 'category'], name='agents_mark_status_59fcc9_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceagent',
            index=models.Index(fields=['is_featured', '-install_count'], name='agents_mark_is_feat_9d4b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceagent',
            index=models.Index(fields=['publisher'], name='agents_mark_publish_f6762c_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceagent',
            index=models.Index(fields=['-rating_average', '-install_count'], name='agents_mark_rating__e433f3_idx'),
        ),
        migrations.AddIndex(
            model_name='agentreview',
            index=models.Index(fields=['marketplace_agent', '-helpful_count'], name='agents_agen_marketp_536214_idx'),
        ),
        migrations.AddIndex(
            model_name='agentreview',
            index=models.Index(fields=['marketplace_agent', '-created_at'], name='agents_agen_marketp_e39b29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentreview',
            unique_together={('marketplace_agent', 'user')},
        ),
        migrations.AddIndex(
            model_name='agentinstallation',
            index=models.Index(fields=['user', 'is_active'], name='agents_agen_user_id_b32ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='agentinstallation',
            index=models.Index(fields=['marketplace_agent'], name='agents_agen_marketp_882c2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentinstallation',
            unique_together={('user', 'marketplace_agent')},
        ),
        migrations.AddIndex(
            model_name='orchestrationexecution',
            index=models.Index(fields=['orchestration', 'status'], name='agents_orch_orchest_473306_idx'),
        ),
        migrations.AddIndex(
            model_name='orchestrationexecution',
            index=models.Index(fields=['created_at'], name='agents_orch_created_cdae60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orchestrationparticipant',
            unique_together={('orchestration', 'agent')},
        ),
        migrations.AddIndex(
            model_name='agentorchestration',
            index=models.Index(fields=['user', 'is_active'], name='agents_agen_user_id_c657a0_idx'),
        ),
        migrations.AddIndex(
            model_name='agentorchestration',
            index=models.Index(fields=['orchestrator_agent'], name='agents_agen_orchest_55e472_idx'),
        ),
        migrations.AddIndex(
            model_name='queryexpansion',
            index=models.Index(fields=['original_query'], name='agents_quer_origina_4f8b37_idx'),
        ),
        migrations.AddIndex(
            model_name='queryexpansion',
            index=models.Index(fields=['agent', 'use_count'], name='agents_quer_agent_i_a71605_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpfulness',
            unique_together={('review', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='toolparameter',
            unique_together={('custom_tool', 'name')},
        ),
    ]
