# Generated by Django 5.2.7 on 2025-10-29 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0004_agent_enabled_tools_agent_tools_config'),
        ('chat', '0006_conversation_channel_identifier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
                ('conversation_count', models.IntegerField(default=0)),
                ('message_count', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('median_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('p95_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('success_rate', models.FloatField(default=0.0)),
                ('error_rate', models.FloatField(default=0.0)),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('use_case_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='agents.agent')),
            ],
            options={
                'ordering': ['-date', '-hour'],
                'indexes': [models.Index(fields=['agent', '-date'], name='analytics_a_agent_i_a6255d_idx'), models.Index(fields=['date'], name='analytics_a_date_819587_idx')],
                'unique_together': {('agent', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ACCESS', 'Access'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=20)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=255)),
                ('object_repr', models.TextField(blank=True)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_a_user_id_77ac48_idx'), models.Index(fields=['action', '-created_at'], name='analytics_a_action_c7cb84_idx'), models.Index(fields=['object_type', 'object_id'], name='analytics_a_object__f92038_idx'), models.Index(fields=['created_at'], name='analytics_a_created_9cacd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('user_messages', models.IntegerField(default=0)),
                ('assistant_messages', models.IntegerField(default=0)),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('avg_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('tool_execution_count', models.IntegerField(default=0)),
                ('escalation_triggered', models.BooleanField(default=False)),
                ('avg_sentiment_score', models.FloatField(blank=True, null=True)),
                ('min_sentiment_score', models.FloatField(blank=True, null=True)),
                ('max_sentiment_score', models.FloatField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_time_seconds', models.IntegerField(blank=True, null=True)),
                ('satisfaction_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='chat.conversation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='analytics_c_convers_809e59_idx')],
            },
        ),
        migrations.CreateModel(
            name='StructuredLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('logger_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('exception_type', models.CharField(blank=True, max_length=255)),
                ('exception_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('memory_usage_mb', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', '-created_at'], name='analytics_s_level_137e93_idx'), models.Index(fields=['logger_name', '-created_at'], name='analytics_s_logger__d75bee_idx'), models.Index(fields=['created_at'], name='analytics_s_created_a23a25_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('agent_created', 'Agent Created'), ('agent_executed', 'Agent Executed'), ('chat_message', 'Chat Message'), ('api_call', 'API Call'), ('tool_execution', 'Tool Execution'), ('document_processed', 'Document Processed'), ('webhook_sent', 'Webhook Sent'), ('escalation', 'Escalation Triggered')], max_length=50)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('llm_provider', models.CharField(blank=True, max_length=50)),
                ('llm_model', models.CharField(blank=True, max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='agents.agent')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_u_user_id_f90ba7_idx'), models.Index(fields=['agent', '-created_at'], name='analytics_u_agent_i_fdca93_idx'), models.Index(fields=['event_type', '-created_at'], name='analytics_u_event_t_e046b2_idx'), models.Index(fields=['created_at'], name='analytics_u_created_5b63bc_idx')],
            },
        ),
    ]
