# Generated by Django 5.2.7 on 2025-10-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional message metadata'),
        ),
    ]
