# Generated by Django 5.2.7 on 2025-10-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='channel_identifier',
            field=models.CharField(blank=True, help_text='External channel ID (email, phone, etc.)', max_length=255),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='channel',
            field=models.CharField(choices=[('web', 'Web Chat'), ('api', 'API'), ('email', 'Email'), ('slack', 'Slack'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='web', max_length=20),
        ),
    ]
