FROM postgres:14

RUN apt-get update && apt-get install -y git build-essential postgresql-server-dev-14

RUN git clone --branch v0.4.1 https://github.com/pgvector/pgvector.git /pgvector \
    && cd /pgvector \
    && make \
    && make install \
    && rm -rf /pgvector

