# Generated by Django 5.2.7 on 2025-10-20 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this integration', max_length=255, verbose_name='name')),
                ('integration_type', models.CharField(choices=[('webhook', 'Webhook'), ('email', 'Email'), ('slack', 'Slack'), ('sms', 'SMS/Twilio'), ('zapier', 'Zapier'), ('crm', 'CRM (Salesforce/HubSpot)'), ('calendar', 'Calendar (Google/Outlook)'), ('zendesk', 'Zendesk'), ('custom', 'Custom API')], help_text='Type of integration', max_length=20, verbose_name='integration type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('pending', 'Pending Setup')], default='pending', help_text='Current status of integration', max_length=20, verbose_name='status')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Integration-specific configuration (API keys, URLs, etc.)', verbose_name='configuration')),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook endpoint URL', max_length=500, null=True, verbose_name='webhook URL')),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for webhook signature verification', max_length=255, null=True, verbose_name='webhook secret')),
                ('events', models.JSONField(blank=True, default=list, help_text='List of events that trigger this integration', verbose_name='events')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this integration is active', verbose_name='is active')),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='When this integration was last triggered', null=True, verbose_name='last triggered at')),
                ('error_message', models.TextField(blank=True, help_text='Last error message if status is error', verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='agents.agent')),
            ],
            options={
                'verbose_name': 'integration',
                'verbose_name_plural': 'integrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft'), ('slack', 'Slack'), ('github', 'GitHub'), ('salesforce', 'Salesforce')], max_length=20, verbose_name='provider')),
                ('provider_user_id', models.CharField(help_text='User ID from the OAuth provider', max_length=255, verbose_name='provider user ID')),
                ('access_token', models.TextField(help_text='OAuth access token (encrypted in production)', verbose_name='access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token (encrypted in production)', verbose_name='refresh token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='token expires at')),
                ('scopes', models.JSONField(default=list, help_text='OAuth scopes granted', verbose_name='scopes')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth connection',
                'verbose_name_plural': 'OAuth connections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Type of event that triggered webhook', max_length=100, verbose_name='event type')),
                ('payload', models.JSONField(default=dict, help_text='Request payload sent to webhook', verbose_name='payload')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('retry', 'Retry')], default='pending', max_length=20, verbose_name='status')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP status code')),
                ('response', models.JSONField(blank=True, default=dict, help_text='Response from webhook endpoint', verbose_name='response')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed', verbose_name='error message')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts', verbose_name='retry count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='integrations.integration')),
            ],
            options={
                'verbose_name': 'webhook log',
                'verbose_name_plural': 'webhook logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=255, verbose_name='name')),
                ('key', models.CharField(help_text='The actual API key', max_length=64, unique=True, verbose_name='key')),
                ('scopes', models.JSONField(default=list, help_text='API scopes/permissions for this key', verbose_name='scopes')),
                ('rate_limit', models.IntegerField(default=1000, help_text='Requests per hour allowed', verbose_name='rate limit')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('usage_count', models.IntegerField(default=0, help_text='Total number of API calls made with this key', verbose_name='usage count')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this API key expires (null = never)', null=True, verbose_name='expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='integration_user_id_51a905_idx'), models.Index(fields=['key'], name='integration_key_868b48_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['agent', 'integration_type'], name='integration_agent_i_fe9e72_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['status'], name='integration_status_86f514_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthconnection',
            index=models.Index(fields=['user', 'provider'], name='integration_user_id_388d49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='oauthconnection',
            unique_together={('user', 'provider')},
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['integration', '-created_at'], name='integration_integra_ae7b30_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['status'], name='integration_status_f21de1_idx'),
        ),
    ]
