# Generated by Django 5.2.7 on 2025-11-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('agent_created', 'Agent Created'), ('agent_deleted', 'Agent Deleted'), ('agent_deployed', 'Agent Deployed'), ('agent_error', 'Agent Error'), ('conversation_started', 'Conversation Started'), ('message_received', 'Message Received'), ('escalation_triggered', 'Escalation Triggered'), ('performance_alert', 'Performance Alert'), ('usage_limit', 'Usage Limit'), ('integration_connected', 'Integration Connected'), ('integration_failed', 'Integration Failed'), ('document_processed', 'Document Processed'), ('webhook_failed', 'Webhook Failed'), ('system_update', 'System Update')], db_index=True, max_length=50),
        ),
    ]
